class StudentMarks{
	public static void main(String args[]){
		String name_1 = "Narasimha A";
		int computers_1 = 82;
		int drawing_1 = 77;
		int m1_1 = 83;
		int m2_1 = 87;
		int m3_1 = 81;
		int m4_1 = 78;
		int physics_1= 80;
		int chemistry_1 = 85;
		int english_1 = 82;
		float max_perc = 0.0f;
		System.out.println("Name: "+name_1);
		System.out.println("Computers: "+computers_1);
		System.out.println("Drawing: "+drawing_1);
		System.out.println("M1: "+m1_1);
		System.out.println("M2: "+m2_1);
		System.out.println("M3: "+m3_1);
		System.out.println("M4: "+m4_1);
		System.out.println("Physics: "+physics_1);
		System.out.println("Chemistry: "+chemistry_1);
		System.out.println("English: "+english_1);
		int sum = computers_1 + drawing_1+m1_1+m2_1+m3_1+m4_1+physics_1+chemistry_1+english_1;
		System.out.println("Total Marks: "+sum);
		float per_1 = (sum/900.0f)*100;
		max_perc = (per_1>max_perc)?per_1:max_perc;
		System.out.println("Percentage :"+per_1);
		System.out.println("_____________________________________");

		String name_2 = "Hemanth Ch";
		int computers_2 = 90;
		int drawing_2 = 82;
		int m1_2 = 86;
		int m2_2 = 89;
		int m3_2 = 84;
		int m4_2 = 77;
		int physics_2= 83;
		int chemistry_2 = 78;
		int english_2 = 85;
		System.out.println("Name: "+name_2);
		System.out.println("Computers: "+computers_2);
		System.out.println("Drawing: "+drawing_2);
		System.out.println("M1: "+m1_2);
		System.out.println("M2: "+m2_2);
		System.out.println("M3: "+m3_2);
		System.out.println("M4: "+m4_2);
		System.out.println("Physics: "+physics_2);
		System.out.println("Chemistry: "+chemistry_2);
		System.out.println("English: "+english_2);
		sum = computers_2 + drawing_2+m1_2+m2_2+m3_2+m4_2+physics_2+chemistry_2+english_2;
		System.out.println("Total Marks: "+sum);
		float per_2 = (sum/900.0f)*100;
		max_perc = (per_2>max_perc)?per_2:max_perc;
		System.out.println("Percentage :"+per_2);
		System.out.println("_____________________________________");

		String name_3 = "Sumanth M";
		int computers_3 = 75;
		int drawing_3 = 80;
		int m1_3 = 79;
		int m2_3 = 85;
		int m3_3 = 88;
		int m4_3 = 82;
		int physics_3= 77;
		int chemistry_3 = 80;
		int english_3= 79;
		System.out.println("Name: "+name_3);
		System.out.println("Computers: "+computers_3);
		System.out.println("Drawing: "+drawing_3);
		System.out.println("M1: "+m1_3);
		System.out.println("M2: "+m2_3);
		System.out.println("M3: "+m3_3);
		System.out.println("M4: "+m4_3);
		System.out.println("Physics: "+physics_3);
		System.out.println("Chemistry: "+chemistry_3);
		System.out.println("English: "+english_3);
		sum = computers_3 + drawing_3+m1_3+m2_3+m3_3+m4_3+physics_3+chemistry_3+english_3;
		System.out.println("Total Marks: "+sum);
		float per_3 = (sum/900.0f)*100;
		max_perc = (per_3>max_perc)?per_3:max_perc;
		System.out.println("Percentage :"+per_3);
		System.out.println("_____________________________________");

		String name_4= "Mohith Sai K";
		int computers_4 = 82;
		int drawing_4 = 77;
		int m1_4 = 83;
		int m2_4 = 87;
		int m3_4 = 81;
		int m4_4 = 78;
		int physics_4= 80;
		int chemistry_4 = 85;
		int english_4 = 82;
		System.out.println("Name: "+name_4);
		System.out.println("Computers: "+computers_4);
		System.out.println("Drawing: "+drawing_4);
		System.out.println("M1: "+m1_4);
		System.out.println("M2: "+m2_4);
		System.out.println("M3: "+m3_4);
		System.out.println("M4: "+m4_4);
		System.out.println("Physics: "+physics_4);
		System.out.println("Chemistry: "+chemistry_4);
		System.out.println("English: "+english_4);
		sum = computers_4 + drawing_4+m1_4+m2_4+m3_4+m4_4+physics_4+chemistry_4+english_4;
		System.out.println("Total Marks: "+sum);
		float per_4 = (sum/900.0f)*100;
		max_perc = (per_4>max_perc)?per_4:max_perc;
		System.out.println("Percentage :"+per_4);
		System.out.println("_____________________________________");

		String name_5 = "Vijaya Lakshmi P";
		int computers_5 = 88;
		int drawing_5 = 84;
		int m1_5 = 85;
		int m2_5 = 90;
		int m3_5 = 89;
		int m4_5 = 81;
		int physics_5= 82;
		int chemistry_5 = 87;
		int english_5 = 86;
		System.out.println("Name: "+name_5);
		System.out.println("Computers: "+computers_5);
		System.out.println("Drawing: "+drawing_5);
		System.out.println("M1: "+m1_5);
		System.out.println("M2: "+m2_5);
		System.out.println("M3: "+m3_5);
		System.out.println("M4: "+m4_5);
		System.out.println("Physics: "+physics_5);
		System.out.println("Chemistry: "+chemistry_5);
		System.out.println("English: "+english_5);
		sum = computers_5 + drawing_5+m1_5+m2_5+m3_5+m4_5+physics_5+chemistry_5+english_5;
		System.out.println("Total Marks: "+sum);
		float per_5 = (sum/900.0f)*100;
		max_perc = (per_5>max_perc)?per_5:max_perc;
		System.out.println("Percentage :"+per_5);
		System.out.println("_____________________________________");

		String name_6= "Kavya Sri K";
		int computers_6 = 79;
		int drawing_6= 75;
		int m1_6 = 80;
		int m2_6 = 82;
		int m3_6 = 83;
		int m4_6 = 79;
		int physics_6= 78;
		int chemistry_6 = 81;
		int english_6 = 80;
		System.out.println("Name: "+name_6);
		System.out.println("Computers: "+computers_6);
		System.out.println("Drawing: "+drawing_6);
		System.out.println("M1: "+m1_6);
		System.out.println("M2: "+m2_6);
		System.out.println("M3: "+m3_6);
		System.out.println("M4: "+m4_6);
		System.out.println("Physics: "+physics_6);
		System.out.println("Chemistry: "+chemistry_6);
		System.out.println("English: "+english_6);
		sum = computers_6 + drawing_6+m1_6+m2_6+m3_6+m4_6+physics_6+chemistry_6+english_6;
		System.out.println("Total Marks: "+sum);
		float per_6 = (sum/900.0f)*100;
		max_perc = (per_6>max_perc)?per_6:max_perc;
		System.out.println("Percentage :"+per_6);
		System.out.println("_____________________________________");

		String name_7 = "Akhila D";
		int computers_7 = 84;
		int drawing_7 = 79;
		int m1_7 = 82;
		int m2_7 = 85;
		int m3_7 = 86;
		int m4_7 = 80;
		int physics_7= 79;
		int chemistry_7 = 83;
		int english_7 = 81;
		System.out.println("Name: "+name_7);
		System.out.println("Computers: "+computers_7);
		System.out.println("Drawing: "+drawing_7);
		System.out.println("M1: "+m1_7);
		System.out.println("M2: "+m2_7);
		System.out.println("M3: "+m3_7);
		System.out.println("M4: "+m4_7);
		System.out.println("Physics: "+physics_7);
		System.out.println("Chemistry: "+chemistry_7);
		System.out.println("English: "+english_7);
		sum = computers_7 + drawing_7+m1_7+m2_7+m3_7+m4_7+physics_7+chemistry_7+english_7;
		System.out.println("Total Marks: "+sum);
		float per_7 = (sum/900.0f)*100;
		max_perc = (per_7>max_perc)?per_7:max_perc;
		System.out.println("Percentage :"+per_7);
		System.out.println("_____________________________________");

		String name_8 = "Sai Charan P";
		int computers_8 = 76;
		int drawing_8 = 81;
		int m1_8 = 77;
		int m2_8 = 84;
		int m3_8 = 80;
		int m4_8 = 82;
		int physics_8= 78;
		int chemistry_8 = 79;
		int english_8 = 80;
		System.out.println("Name: "+name_8);
		System.out.println("Computers: "+computers_8);
		System.out.println("Drawing: "+drawing_8);
		System.out.println("M1: "+m1_8);
		System.out.println("M2: "+m2_8);
		System.out.println("M3: "+m3_8);
		System.out.println("M4: "+m4_8);
		System.out.println("Physics: "+physics_8);
		System.out.println("Chemistry: "+chemistry_8);
		System.out.println("English: "+english_8);
		sum = computers_8 + drawing_8+m1_8+m2_8+m3_8+m4_8+physics_8+chemistry_8+english_8;
		System.out.println("Total Marks: "+sum);
		float per_8= (sum/900.0f)*100;
		max_perc = (per_8>max_perc)?per_8:max_perc;
		System.out.println("Percentage :"+per_8);
		System.out.println("_____________________________________");

		String name_9 = "Sathvika A";
		int computers_9 = 89;
		int drawing_9 = 85;
		int m1_9= 87;
		int m2_9 = 90;
		int m3_9 = 84;
		int m4_9 = 88;
		int physics_9= 83;
		int chemistry_9 = 86;
		int english_9 = 87;
		System.out.println("Name: "+name_9);
		System.out.println("Computers: "+computers_9);
		System.out.println("Drawing: "+drawing_9);
		System.out.println("M1: "+m1_9);
		System.out.println("M2: "+m2_9);
		System.out.println("M3: "+m3_9);
		System.out.println("M4: "+m4_9);
		System.out.println("Physics: "+physics_9);
		System.out.println("Chemistry: "+chemistry_9);
		System.out.println("English: "+english_9);
		sum = computers_9 + drawing_9+m1_9+m2_9+m3_9+m4_9+physics_9+chemistry_9+english_9;
		System.out.println("Total Marks: "+sum);
		float per_9 = (sum/900.0f)*100;
		max_perc = (per_9>max_perc)?per_9:max_perc;
		System.out.println("Percentage :"+per_9);
		System.out.println("_____________________________________");

		String name_10 = "Karishma Md";
		int computers_10 = 77;
		int drawing_10 = 80;
		int m1_10 = 78;
		int m2_10 = 83;
		int m3_10 = 81;
		int m4_10 = 79;
		int physics_10= 76;
		int chemistry_10 = 80;
		int english_10 = 78;
		System.out.println("Name: "+name_10);
		System.out.println("Computers: "+computers_10);
		System.out.println("Drawing: "+drawing_10);
		System.out.println("M1: "+m1_10);
		System.out.println("M2: "+m2_10);
		System.out.println("M3: "+m3_10);
		System.out.println("M4: "+m4_10);
		System.out.println("Physics: "+physics_10);
		System.out.println("Chemistry: "+chemistry_10);
		System.out.println("English: "+english_10);
		sum = computers_10 + drawing_10+m1_10+m2_10+m3_10+m4_10+physics_10+chemistry_10+english_10;
		System.out.println("Total Marks: "+sum);
		float per_10 = (sum/900.0f)*100;
		max_perc = (per_10>max_perc)?per_10:max_perc;
		System.out.println("Percentage :"+per_10);
		System.out.println("_____________________________________");

		String name_11 = "Aparna K";
		int computers_11 = 83;
		int drawing_11 = 79;
		int m1_11 = 82;
		int m2_11 = 88;
		int m3_11 = 80;
		int m4_11 = 85;
		int physics_11= 81;
		int chemistry_11 = 84;
		int english_11 = 83;
		System.out.println("Name: "+name_11);
		System.out.println("Computers: "+computers_11);
		System.out.println("Drawing: "+drawing_11);
		System.out.println("M1: "+m1_11);
		System.out.println("M2: "+m2_11);
		System.out.println("M3: "+m3_11);
		System.out.println("M4: "+m4_11);
		System.out.println("Physics: "+physics_11);
		System.out.println("Chemistry: "+chemistry_11);
		System.out.println("English: "+english_11);
		sum = computers_11 + drawing_11+m1_11+m2_11+m3_11+m4_11+physics_11+chemistry_11+english_11;
		System.out.println("Total Marks: "+sum);
		float per_11 = (sum/900.0f)*100;
		max_perc = (per_11>max_perc)?per_11:max_perc;
		System.out.println("Percentage :"+per_11);
		System.out.println("_____________________________________");

		String name_12 = "Laxmi Chaitanya L";
		int computers_12 = 85;
		int drawing_12 = 81;
		int m1_12 = 84;
		int m2_12 = 89;
		int m3_12 = 82;
		int m4_12 = 86;
		int physics_12= 83;
		int chemistry_12 = 87;
		int english_12 = 85;
		System.out.println("Name: "+name_12);
		System.out.println("Computers: "+computers_12);
		System.out.println("Drawing: "+drawing_12);
		System.out.println("M1: "+m1_12);
		System.out.println("M2: "+m2_12);
		System.out.println("M3: "+m3_12);
		System.out.println("M4: "+m4_12);
		System.out.println("Physics: "+physics_12);
		System.out.println("Chemistry: "+chemistry_12);
		System.out.println("English: "+english_12);
		sum = computers_2 + drawing_12+m1_12+m2_12+m3_12+m4_12+physics_12+chemistry_12+english_12;
		System.out.println("Total Marks: "+sum);
		float per_12 = (sum/900.0f)*100;
		max_perc = (per_12>max_perc)?per_12:max_perc;
		System.out.println("Percentage :"+per_12);
		System.out.println("_____________________________________");

		String name_13 = "Rahul R";
		int computers_13 = 78;
		int drawing_13 = 76;
		int m1_13 = 79;
		int m2_13 = 81;
		int m3_13 = 80;
		int m4_13 = 77;
		int physics_13= 76;
		int chemistry_13 = 78;
		int english_13 = 79;
		System.out.println("Name: "+name_13);
		System.out.println("Computers: "+computers_13);
		System.out.println("Drawing: "+drawing_13);
		System.out.println("M1: "+m1_13);
		System.out.println("M2: "+m2_13);
		System.out.println("M3: "+m3_13);
		System.out.println("M4: "+m4_13);
		System.out.println("Physics: "+physics_13);
		System.out.println("Chemistry: "+chemistry_13);
		System.out.println("English: "+english_13);
		sum = computers_13 + drawing_13+m1_13+m2_13+m3_13+m4_13+physics_13+chemistry_13+english_13;
		System.out.println("Total Marks: "+sum);
		float per_13 = (sum/900.0f)*100;
		max_perc = (per_13>max_perc)?per_13:max_perc;
		System.out.println("Percentage :"+per_13);
		System.out.println("_____________________________________");

		String name_14 = "Sai Kumar J";
		int computers_14 = 80;
		int drawing_14 = 82;
		int m1_14 = 81;
		int m2_14 = 83;
		int m3_14 = 84;
		int m4_14 = 80;
		int physics_14= 79;
		int chemistry_14 = 82;
		int english_14 = 81;
		System.out.println("Name: "+name_14);
		System.out.println("Computers: "+computers_14);
		System.out.println("Drawing: "+drawing_14);
		System.out.println("M1: "+m1_14);
		System.out.println("M2: "+m2_14);
		System.out.println("M3: "+m3_14);
		System.out.println("M4: "+m4_14);
		System.out.println("Physics: "+physics_14);
		System.out.println("Chemistry: "+chemistry_14);
		System.out.println("English: "+english_14);
		sum = computers_14 + drawing_14+m1_14+m2_14+m3_14+m4_14+physics_14+chemistry_14+english_14;
		System.out.println("Total Marks: "+sum);
		float per_14 = (sum/900.0f)*100;
		max_perc = (per_14>max_perc)?per_14:max_perc;
		System.out.println("Percentage :"+per_14);
		System.out.println("_____________________________________");
		System.out.println("Class Highest Percentage is: "+max_perc);
		if(max_perc == per_1)
			System.out.println("Student with maximum percentage:"+name_1);
		if(max_perc == per_2)
			System.out.println("Student with maximum percentage:"+name_2);
		if(max_perc == per_3)
			System.out.println("Student with maximum percentage:"+name_3);
		if(max_perc == per_4)
			System.out.println("Student with maximum percentage:"+name_4);
		if(max_perc == per_5)
			System.out.println("Student with maximum percentage:"+name_5);
		if(max_perc == per_6)
			System.out.println("Student with maximum percentage:"+name_6);
		if(max_perc == per_7)
			System.out.println("Student with maximum percentage:"+name_7);
		if(max_perc == per_8)
			System.out.println("Student with maximum percentage:"+name_8);
		if(max_perc == per_9)
			System.out.println("Student with maximum percentage:"+name_9);
		if(max_perc == per_10)
			System.out.println("Student with maximum percentage:"+name_10);
		if(max_perc == per_11)
			System.out.println("Student with maximum percentage:"+name_11);
		if(max_perc == per_12)
			System.out.println("Student with maximum percentage:"+name_12);
		if(max_perc == per_13)
			System.out.println("Student with maximum percentage:"+name_13);
		if(max_perc == per_14)
			System.out.println("Student with maximum percentage:"+name_14);
	}
}