public class StudentDetailsTask{
	public static void main(String[] args){

        String name = "Narasimha";
	int computers = 85;
	int drawing = 78;
	int m1 = 88;
	int m2 =92;
	int m3 = 80;
	int m4 = 76;
        int physics = 81;
        int chemistry = 79;
        int english = 84;
	final float total = 900f;
       int marks = computers+drawing+m1+m2+m3+m4+physics+chemistry+english;
       float perc = (marks/total)*100;
	System.out.println("Student name is :"+name);
        System.out.println("Total marks is :"+marks);
	System.out.println("Percentage is : "+perc);
      System.out.println("------------------------------------------------------------------");
  
		String name1 = "Hemanth Ch";
	int computers1 = 90;
	int drawing1 = 82;
	int m11 = 86;
	int m21 =89;
	int m31 = 84;
	int m41 = 77;
        int physics1 = 83;
        int chemistry1 = 78;
        int english1 = 85;
       int marks1 = computers1+drawing+m11+m21+m31+m41+physics1+chemistry1+english1;
       float perc1 = (marks1/total)*100;
	System.out.println("Student name is :"+name1);
        System.out.println("Total marks is :"+marks1);
	System.out.println("Percentage is : "+perc1);
System.out.println("------------------------------------------------------------------");
		
		String name2 = "Sumanth M";
	int computers2 = 75;
	int drawing2 = 80;
	int m12 = 79;
	int m22 =85;
	int m32 = 88;
	int m42 = 82;
        int physics2 = 77;
        int chemistry2 = 80;
        int english2 = 79;
       int marks2 = computers2+drawing2+m12+m22+m32+m42+physics2+chemistry2+english2;
       float perc2 = (marks2/total)*100;
	System.out.println("Student name is :"+name2);
        System.out.println("Total marks is :"+marks2);
	System.out.println("Percentage is : "+perc2);
System.out.println("------------------------------------------------------------------");
		
		String name3 = "Mohith Sai";
	int computers3 = 82;
	int drawing3 = 77;
	int m13 = 83;
	int m23=87;
	int m33 = 81;
	int m43 = 78;
        int physics3 = 80;
        int chemistry3 = 85;
        int english3 = 82;
       int marks3 = computers+drawing+m1+m2+m3+m4+physics+chemistry+english;
       float perc3 = (marks3/total)*100;
	System.out.println("Student name is :"+name3);
        System.out.println("Total marks is :"+marks3);
	System.out.println("Percentage is : "+perc3);
System.out.println("------------------------------------------------------------------");
    
		String name4 = "Vijaya Lakshmi P";
	int computers4 = 88;
	int drawing4 = 84;
	int m14 = 85;
	int m24 =90;
	int m34 = 89;
	int m44 = 81;
        int physics4 = 82;
        int chemistry4 = 87;
        int english4 = 86;
       int marks4 = computers4+drawing4+m14+m24+m34+m44+physics4+chemistry4+english4;
       float perc4 = (marks4/total)*100;
	System.out.println("Student name is :"+name4);
        System.out.println("Total marks is :"+marks4);
	System.out.println("Percentage is : "+perc4);
System.out.println("------------------------------------------------------------------");
	
	String name5 = "Kavya Sri K";
	int computers5 = 79;
	int drawing5 = 75;
	int m15 = 80;
	int m25 =82;
	int m35 = 83;
	int m45 = 79;
        int physics5 = 78;
        int chemistry5 = 81;
        int english5 = 80;
       int marks5 = computers5+drawing5+m15+m25+m35+m45+physics5+chemistry5+english5;
       float perc5 = (marks5/total)*100;
	System.out.println("Student name is :"+name5);
        System.out.println("Total marks is :"+marks5);
	System.out.println("Percentage is : "+perc5);
System.out.println("------------------------------------------------------------------");
	
		String name6 = "Akhila D";
	int computers6 = 84;
	int drawing6 = 79;
	int m16 = 82;
	int m26 =85;
	int m36 = 86;
	int m46 = 80;
        int physics6 = 79;
        int chemistry6 = 83;
        int english6 = 81;
       int marks6 = computers6+drawing6+m16+m26+m36+m46+physics6+chemistry6+english6;
       float perc6 = (marks6/total)*100;
	System.out.println("Student name is :"+name6);
        System.out.println("Total marks is :"+marks6);
	System.out.println("Percentage is : "+perc6);
System.out.println("------------------------------------------------------------------");

		
		String name7 = "Sai Charan P";
	int computers7 = 76;
	int drawing7 = 81;
	int m17 = 77;
	int m27 =84;
	int m37 = 80;
	int m47 = 82;
        int physics7 = 78;
        int chemistry7 = 79;
        int english7 = 80;
       int marks7 = computers7+drawing7+m17+m27+m37+m47+physics7+chemistry7+english7;
       float perc7 = (marks7/total)*100;
System.out.println("Student name is :"+name7);
        System.out.println("Total marks is :"+marks7);
	System.out.println("Percentage is : "+perc7);
System.out.println("------------------------------------------------------------------");

		String name8 = "Sathvika A";
	int computers8 = 89;
	int drawing8 = 85;
	int m18 = 87;
	int m28 =90;
	int m38 = 84;
	int m48 = 88;
        int physics8 = 83;
        int chemistry8 = 86;
        int english8 = 87;
       int marks8 = computers8+drawing8+m18+m28+m38+m48+physics8+chemistry8+english8;
       float perc8 = (marks8/total)*100;
	System.out.println("Student name is :"+name8);
        System.out.println("Total marks is :"+marks8);
	System.out.println("Percentage is : "+perc8);
System.out.println("------------------------------------------------------------------");


	String name9 = "Karishma Md";
	int computers9 = 77;
	int drawing9 = 80;
	int m19 = 78;
	int m29 =83;
	int m39 = 81;
	int m49 = 79;
        int physics9 = 76;
        int chemistry9 = 80;
        int english9 = 78;
       int marks9 = computers9+drawing9+m19+m29+m39+m49+physics9+chemistry9+english9;
       float perc9 = (marks9/total)*100;
	System.out.println("Student name is :"+name9);
        System.out.println("Total marks is :"+marks9);
	System.out.println("Percentage is : "+perc9);
System.out.println("------------------------------------------------------------------");

		String name0 = "Aparna K";
	int computers0 = 83;
	int drawing0 = 79;
	int m10 = 82;
	int m20 =88;
	int m30 = 80;
	int m40 = 85;
        int physics0= 81;
        int chemistry0 = 84;
        int english0 = 83;
       int marks0 = computers0+drawing0+m10+m20+m30+m40+physics0+chemistry0+english0;
       float perc0 = (marks0/total)*100;
	System.out.println("Student name is :"+name0);
        System.out.println("Total marks is :"+marks0);
	System.out.println("Percentage is : "+perc0);
System.out.println("------------------------------------------------------------------");

	String name11 = "Lakshmi Chaitanya L";
	int computers11 = 85;
	int drawing11 = 81;
	int m111 = 84;
	int m211 =89;
	int m311 = 82;
	int m411 = 86;
        int physics11 = 83;
        int chemistry11 = 87;
        int english11 = 85;
       int marks11 = computers11+drawing11+m11+m211+m311+m411+physics11+chemistry11+english11;
       float perc11 = (marks11/total)*100;
	System.out.println("Student name is :"+name11);
        System.out.println("Total marks is :"+marks11);
	System.out.println("Percentage is : "+perc11);
System.out.println("------------------------------------------------------------------");

	String name12 = "Rahul R";
	int computers12 = 78;
	int drawing12 = 76;
	int m112 = 79;
	int m212 =81;
	int m312 = 80;
	int m412 = 77;
        int physics12 = 76;
        int chemistry12 = 78;
        int english12 = 79;
       int marks12 = computers12+drawing12+m112+m212+m312+m412+physics12+chemistry12+english12;
       float perc12 = (marks12/total)*100;
	System.out.println("Student name is :"+name12);
        System.out.println("Total marks is :"+marks12);
	System.out.println("Percentage is : "+perc12);
System.out.println("------------------------------------------------------------------");
 
	String name13 = "SaiKumar J";
	int computers13 = 80;
	int drawing13 = 82;
	int m113 = 81;
	int m213 =83;
	int m313 = 84;
	int m413 = 80;
        int physics13 = 79;
        int chemistry13 = 82;
        int english13 = 81;
       int marks13 = computers+drawing+m1+m2+m3+m4+physics+chemistry+english;
       float perc13 = (marks13/total)*100;
	System.out.println("Student name is :"+name13);
        System.out.println("Total marks is :"+marks13);
	System.out.println("Percentage is : "+perc13);
System.out.println("------------------------------------------------------------------");
 