public class StudentDetails{
    public static void main(String[] args){
        String name = "Narasimha A";
        System.out.println(name);
        int computer = 85; 
        int drawing = 78; 
        int m1 = 88; 
        int m2 = 87; 
        int m3 = 80; 
        int m4 = 78;
        int physics = 95;
        int chemistry = 68; 
        int english = 98;
        int totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        float percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
         name = "Akhila reddy";
        System.out.println(name);
        computer = 89; 
         drawing = 67; 
         m1 = 98; 
         m2 = 69; 
         m3 = 96; 
         m4 = 64;
         physics = 81;
         chemistry = 80; 
        english = 60;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "vijaya lakshmi";
        System.out.println(name);
        computer = 90; 
         drawing = 90; 
         m1 = 98; 
         m2 = 80; 
         m3 = 97; 
         m4 = 58;
         physics = 100;
         chemistry = 80; 
        english = 63;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "kavya";
        System.out.println(name);
        computer = 90; 
         drawing = 90; 
         m1 = 90; 
         m2 = 60; 
         m3 = 90; 
         m4 = 60;
         physics = 80;
         chemistry = 80; 
        english = 60;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "satwika";
        System.out.println(name);
        computer = 80; 
         drawing = 70; 
         m1 = 77; 
         m2 = 88; 
         m3 = 99; 
         m4 = 66;
         physics = 88;
         chemistry = 80; 
        english = 60;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "Sumanth";
        System.out.println(name);
        computer = 99; 
         drawing = 99; 
         m1 = 99; 
         m2 = 88; 
         m3 = 97; 
         m4 = 66;
         physics = 88;
         chemistry = 80; 
        english = 99;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "Hemanth";
        System.out.println(name);
        computer = 66; 
         drawing = 67; 
         m1 = 68; 
         m2 = 69; 
         m3 = 66; 
         m4 = 64;
         physics = 100;
         chemistry = 100; 
        english = 90;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "Mohith sai";
        System.out.println(name);
        computer = 77; 
         drawing = 77; 
         m1 = 77; 
         m2 = 69; 
         m3 = 77; 
         m4 = 64;
         physics = 77;
         chemistry = 77; 
        english = 80;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "Saicharan";
        System.out.println(name);
        computer = 90; 
         drawing = 67; 
         m1 = 90; 
         m2 = 65; 
         m3 = 69; 
         m4 = 58;
         physics = 98;
         chemistry = 56; 
        english = 60;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "Sai kumar";
        System.out.println(name);
        computer = 89; 
         drawing = 67; 
         m1 = 98; 
         m2 = 69; 
         m3 = 96; 
         m4 = 64;
         physics = 81;
         chemistry = 80; 
        english = 60;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "Rahul";
        System.out.println(name);
        computer = 89; 
         drawing = 67; 
         m1 = 50; 
         m2 = 58; 
         m3 = 60; 
         m4 = 64;
         physics = 81;
         chemistry = 59; 
        english = 89;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "Karishma";
        System.out.println(name);
        computer = 90; 
         drawing = 90; 
         m1 = 90; 
         m2 = 90; 
         m3 = 90; 
         m4 = 90;
         physics = 90;
         chemistry = 90; 
        english = 90;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "Aparna";
        System.out.println(name);
        computer = 58; 
         drawing = 67; 
         m1 = 95; 
         m2 = 69; 
         m3 = 95; 
         m4 = 94;
         physics = 89;
         chemistry = 80; 
        english = 60;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
        name = "Chaitanya";
        System.out.println(name);
        computer = 89; 
         drawing = 67; 
         m1 = 98; 
         m2 = 69; 
         m3 = 69; 
         m4 = 89;
         physics = 81;
         chemistry = 80; 
        english = 89;
        totalstudentmarks = computer+drawing+m1+m2+m3+m4+physics+chemistry+english;
        System.out.println("total marks of a student:+totalstudentmarks");
        percentage = (((float)totalstudentmarks/900)*100);
        System.out.println("percentage:"+ percentage);
        
    }
}