
import java.util.ArrayList;
import java.util.HashMap;

public class Studentmarks {
    public static void main(String[] args) {
        HashMap<String,String>s1 = new HashMap<>();
        s1.put("name","Aparna");
        s1.put("phone","100");
        s1.put("java","80");
        s1.put("sql","50");
        s1.put("js","60");
        s1.put("rollnumber","1");
        s1.put("email","aparna@gmail.com");
        HashMap<String,String>s2 = new HashMap<>();
        s2.put("name","Chaitanya K");
        s2.put("phone","1234567790");
        s2.put("java","55");
        s2.put("sql","58");
        s2.put("js","68");
        s2.put("rollnumber","2");
        s2.put("email","ChaitanyaK@gmail.com");
        HashMap<String,String>s3= new HashMap<>();
        s3.put("name","Chaitanya");
        s3.put("phone","1234567770");
        s3.put("java","59");
        s3.put("sql","67");
        s3.put("js","68");
        s3.put("rollnumber","3");
        s3.put("email","Chaitanya@gmail.com");
        HashMap<String,String>s4= new HashMap<>();
        s4.put("name","Raghu");
        s4.put("phone","9934567770");
        s4.put("java","67");
        s4.put("sql","72");
        s4.put("js","63");
        s4.put("rollnumber","4");
        s4.put("email","raghu@gmail.com");
        HashMap<String,String>s5= new HashMap<>();
        s5.put("name","Rahul");
        s5.put("phone","9984567770");
        s5.put("java","70");
        s5.put("sql","75");
        s5.put("js","68");
        s5.put("rollnumber","5");
        s5.put("email","rahul@gmail.com");
        HashMap<String,String>s6= new HashMap<>();
        s6.put("name","Ramana");
        s6.put("phone","7734567770");
        s6.put("java","67");
        s6.put("sql","79");
        s6.put("js","59");
        s6.put("rollnumber","6");
        s6.put("email","ramana@gmail.com");
        HashMap<String,String>s7= new HashMap<>();
        s7.put("name","Sai charan");
        s7.put("phone","9794567770");
        s7.put("java","99");
        s7.put("sql","99");
        s7.put("js","98");
        s7.put("rollnumber","7");
        s7.put("email","saicharan@gmail.com");
        HashMap<String,String>s8= new HashMap<>();
        s8.put("name","Sai kumar");
        s8.put("phone","8797567770");
        s8.put("java","89");
        s8.put("sql","98");
        s8.put("js","87");
        s8.put("rollnumber","8");
        s8.put("email","saikumar@gmail.com");
        HashMap<String,String>s9= new HashMap<>();
        s9.put("name","Sai deepa");
        s9.put("phone","9392567770");
        s9.put("java","77");
        s9.put("sql","67");
        s9.put("js","76");
        s9.put("rollnumber","9");
        s9.put("email","saideepa@gmail.com");
        HashMap<String,String>s10= new HashMap<>();
        s10.put("name","Kavya");
        s10.put("phone","9392568980");
        s10.put("java","76");
        s10.put("sql","45");
        s10.put("js","78");
        s10.put("rollnumber","10");
        s10.put("email","kavya@gmail.com");
        HashMap<String,String>s11= new HashMap<>();
        s11.put("name","Mohit");
        s11.put("phone","5432167890");
        s11.put("java","95");
        s11.put("sql","90");
        s11.put("js","80");
        s11.put("rollnumber","11");
        s11.put("email","mohith@gmail.com");
        HashMap<String,String>s12 = new HashMap<>();
        s12.put("name","Karishma");
        s12.put("phone","5321467790");
        s12.put("java","75");
        s12.put("sql","68");
        s12.put("js","45");
        s12.put("rollnumber","12");
        s12.put("email","karishma@gmail.com");
        HashMap<String,String>s13= new HashMap<>();
        s13.put("name","Hemanth");
        s13.put("phone","6543217770");
        s13.put("java","89");
        s13.put("sql","86");
        s13.put("js","67");
        s13.put("rollnumber","13");
        s13.put("email","hemanth@gmail.com");
        HashMap<String,String>s14= new HashMap<>();
        s14.put("name","siva");
        s14.put("phone","9934967770");
        s14.put("java","76");
        s14.put("sql","89");
        s14.put("js","53");
        s14.put("rollnumber","14");
        s14.put("email","siva@gmail.com");
        HashMap<String,String>s15= new HashMap<>();
        s15.put("name","kiran");
        s15.put("phone","9984567870");
        s15.put("java","60");
        s15.put("sql","65");
        s15.put("js","60");
        s15.put("rollnumber","15");
        s15.put("email","kiran@gmail.com");
        HashMap<String,String>s16= new HashMap<>();
        s16.put("name","sathvika");
        s16.put("phone","7734467770");
        s16.put("java","76");
        s16.put("sql","97");
        s16.put("js","94");
        s16.put("rollnumber","16");
        s16.put("email","sathvika@gmail.com");
        HashMap<String,String>s17= new HashMap<>();
        s17.put("name","Suvarchala");
        s17.put("phone","9794569870");
        s17.put("java","69");
        s17.put("sql","91");
        s17.put("js","78");
        s17.put("rollnumber","17");
        s17.put("email","suvarchala@gmail.com");
        HashMap<String,String>s18= new HashMap<>();
        s18.put("name","Sumanth");
        s18.put("phone","8797507770");
        s18.put("java","67");
        s18.put("sql","46");
        s18.put("js","57");
        s18.put("rollnumber","18");
        s18.put("email","sumanth@gmail.com");
        HashMap<String,String>s19= new HashMap<>();
        s19.put("name","Vamsi");
        s19.put("phone","9392367770");
        s19.put("java","75");
        s19.put("sql","48");
        s19.put("js","55");
        s19.put("rollnumber","19");
        s19.put("email","vamsi@gmail.com");
        HashMap<String,String>s20= new HashMap<>();
        s20.put("name","vijaya");
        s20.put("phone","9392468980");
        s20.put("java","45");
        s20.put("sql","75");
        s20.put("js","44");
        s20.put("rollnumber","20");
        s20.put("email","vijaya@gmail.com");
        ArrayList<HashMap<String,String>> ListofStudents=new ArrayList<>();
        ListofStudents.add (s1);
        ListofStudents.add (s2);
        ListofStudents.add (s3);
        ListofStudents.add (s4);
        ListofStudents.add (s5);
        ListofStudents.add (s6);
        ListofStudents.add (s7);
        ListofStudents.add (s8);
        ListofStudents.add (s9);
        ListofStudents.add (s10);
        ListofStudents.add (s11);
        ListofStudents.add (s12);
        ListofStudents.add (s13);
        ListofStudents.add (s14);
        ListofStudents.add (s15);
        ListofStudents.add (s16);
        ListofStudents.add (s17);
        ListofStudents.add (s18);
        ListofStudents.add (s19);
        ListofStudents.add (s20);
        for (HashMap<String,String> student : ListofStudents) {
            System.out.println("___________________________________________________________________");
            System.out.println("Name: " + student.get("name"));
            System.out.println("Phone: " + student.get("phone"));
            System.out.println("Java Score: " + student.get("java"));
            System.out.println("SQL Score: " + student.get("sql"));
            System.out.println("JS Score: " + student.get("js"));
            System.out.println("Roll Number: " + student.get("rollnumber"));
            System.out.println("Email: " + student.get("email"));
            System.out.println();
        }

       
}
}